import "server-only";

import { mkdir, readFile, writeFile, access, rename } from "node:fs/promises";
import { constants as FsConstants } from "node:fs";
import { dirname } from "node:path";

import { logDebugEvent } from "@/lib/debug/logger";
import { getKcbCoinsConfigUrl, getKcbIconsBaseUrl } from "@/lib/kcb/env";
import { kcbPaths } from "@/lib/kcb/paths";
import {
  BootstrapConfig,
  BootstrapStatusState,
  CoinSourceConfig,
  GuiPolicy,
  LastApplyState,
} from "@/lib/kcb/types";

async function exists(path: string): Promise<boolean> {
  try {
    await access(path, FsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function readJsonFile<T>(path: string): Promise<T> {
  const raw = await readFile(path, "utf8");
  try {
    return JSON.parse(raw) as T;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Invalid JSON in ${path}: ${message}`);
  }
}

export async function writeJsonFile(path: string, value: unknown): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const tmpPath = `${path}.tmp.${process.pid}.${Date.now()}`;
  const payload = `${JSON.stringify(value, null, 2)}\n`;
  await writeFile(tmpPath, payload, "utf8");
  await rename(tmpPath, path);
}

function defaultBootstrapConfig(): BootstrapConfig {
  return {
    version: 1,
    kcb_log_level: "info",
    coins: [],
    simple_mm: {
      enabled: false,
      start_on_apply: false,
    },
  };
}

function defaultCoinSources(): CoinSourceConfig {
  return {
    coins_config_url: getKcbCoinsConfigUrl(),
    icons_base_url: getKcbIconsBaseUrl(),
  };
}

function defaultGuiPolicy(): GuiPolicy {
  return {
    version: 1,
    trading_pairs: [],
  };
}

function defaultBootstrapStatus(): BootstrapStatusState {
  return {
    updated_at: new Date().toISOString(),
    status: "idle",
    message: "No bootstrap apply has been executed yet.",
  };
}

function defaultLastApply(): LastApplyState {
  return {
    applied_at: new Date(0).toISOString(),
    ok: false,
    summary: {},
    errors: [],
  };
}

export async function ensureKcbLayout(): Promise<void> {
  await mkdir(kcbPaths.root(), { recursive: true });
  await mkdir(kcbPaths.configDir(), { recursive: true });
  await mkdir(kcbPaths.cacheDir(), { recursive: true });
  await mkdir(kcbPaths.stateDir(), { recursive: true });
  await mkdir(kcbPaths.logsDir(), { recursive: true });
  await mkdir(kcbPaths.cacheCoinsDir(), { recursive: true });
  await mkdir(kcbPaths.cacheIconsDir(), { recursive: true });

  if (!(await exists(kcbPaths.bootstrapConfig()))) {
    await writeJsonFile(kcbPaths.bootstrapConfig(), defaultBootstrapConfig());
  }

  if (!(await exists(kcbPaths.capabilitiesLocal()))) {
    await writeJsonFile(kcbPaths.capabilitiesLocal(), {
      notes: "Local capability overrides. Add only deployment-specific constraints.",
      overrides: {},
    });
  }

  if (!(await exists(kcbPaths.coinSources()))) {
    await writeJsonFile(kcbPaths.coinSources(), defaultCoinSources());
  }

  if (!(await exists(kcbPaths.guiPolicy()))) {
    await writeJsonFile(kcbPaths.guiPolicy(), defaultGuiPolicy());
  }

  if (!(await exists(kcbPaths.bootstrapStatus()))) {
    await writeJsonFile(kcbPaths.bootstrapStatus(), defaultBootstrapStatus());
  }

  if (!(await exists(kcbPaths.lastApply()))) {
    await writeJsonFile(kcbPaths.lastApply(), defaultLastApply());
  }

  if (!(await exists(kcbPaths.resolvedCapabilities()))) {
    await writeJsonFile(kcbPaths.resolvedCapabilities(), {
      resolved_at: new Date().toISOString(),
      capabilities: {},
      notes: "Generated by KCB capability resolver",
    });
  }

  await logDebugEvent({
    severity: "debug",
    title: "KCB layout ensured",
    body: "Verified KCB config/cache/state/logs directory structure",
    details: { root: kcbPaths.root() },
  });
}
